import { createElement } from "react";
import { DisclaimerIllustration } from "../components/illustrations/DisclaimerIllustration";
import type { LyricsSection } from "./types";

export const RAM_BOX_LYRICS: readonly LyricsSection[] = [
  {
    sectionId: 1,
    timestamp: "00:00.00",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: createElement(DisclaimerIllustration),
  },
  {
    sectionId: 2,
    timestamp: "00:14.25",
    line: "[Voice] Are You Ready?",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 1000,
    illustrateWith: "[Voice] Are You Ready?",
  },
  {
    sectionId: 3,
    timestamp: "00:23.00",
    line: "[Voice] Let's get ready to rumble!",
    offsetEnter: -500,
    enterDuration: 1000,
    exitDuration: 175,
    illustrateWith: "[Voice] Let's get ready to rumble!",
  },
  {
    sectionId: 4,
    timestamp: "00:27.65",
    line: "Вся жизнь — это",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Вся жизнь — это",
  },
  {
    sectionId: 5,
    timestamp: "00:28.35",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 6,
    timestamp: "00:29.05",
    line: "Затяжной, мучительный",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Затяжной, мучительный",
  },
  {
    sectionId: 7,
    timestamp: "00:30.20",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 8,
    timestamp: "00:30.85",
    line: "Агрессивный, жертвенный",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Агрессивный, жертвенный",
  },
  {
    sectionId: 9,
    timestamp: "00:32.00",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 10,
    timestamp: "00:32.55",
    line: "И не раз переломанный нос,",
    offsetEnter: -500,
    enterDuration: 300,
    exitDuration: 200,
    illustrateWith: "И не раз переломанный нос,",
  },
  {
    sectionId: 11,
    timestamp: "00:33.70",
    line: "Это лишь минимум, что может дать тебе",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Это лишь минимум, что может дать тебе",
  },
  {
    sectionId: 12,
    timestamp: "00:35.50",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 13,
    timestamp: "00:36.20",
    line: "Каждый день как раунд в износ",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Каждый день как раунд в износ",
  },
  {
    sectionId: 14,
    timestamp: "00:37.50",
    line: "И не важно мне, B-Hope, Али, Тайсон, Рой Джонс",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "И не важно мне, B-Hope, Али, Тайсон, Рой Джонс",
  },
  {
    sectionId: 15,
    timestamp: "00:39.75",
    line: "Этот бой будет длиться пока не услышим последний гонг, — это",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Этот бой будет длиться пока не услышим последний гонг, — это",
  },
  {
    sectionId: 16,
    timestamp: "00:42.65",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 17,
    timestamp: "00:43.10",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 18,
    timestamp: "00:43.60",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 19,
    timestamp: "00:44.05",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 20,
    timestamp: "00:44.50",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 21,
    timestamp: "00:44.80",
    line: "От этого нам некуда деться",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "От этого нам некуда деться",
  },
  {
    sectionId: 22,
    timestamp: "00:46.25",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 23,
    timestamp: "00:46.70",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 24,
    timestamp: "00:47.15",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 25,
    timestamp: "00:47.60",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 26,
    timestamp: "00:48.05",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 27,
    timestamp: "00:48.42",
    line: "Только не кидай полотенце",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Только не кидай полотенце",
  },
  {
    sectionId: 28,
    timestamp: "00:49.65",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 29,
    timestamp: "00:50.10",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 30,
    timestamp: "00:50.55",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 31,
    timestamp: "00:51.00",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 32,
    timestamp: "00:51.45",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 33,
    timestamp: "00:51.75",
    line: "Я готов оказаться в замесе",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Я готов оказаться в замесе",
  },
  {
    sectionId: 34,
    timestamp: "00:53.35",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 35,
    timestamp: "00:53.78",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 36,
    timestamp: "00:54.21",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 37,
    timestamp: "00:54.64",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 38,
    timestamp: "00:55.07",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 39,
    timestamp: "00:55.30",
    line: "Только не кидай…",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Только не кидай…",
  },
  {
    sectionId: 40,
    timestamp: "00:56.20",
    line: "Прогнуться без боя или пробиваться смуте на зло?",
    offsetEnter: -200,
    enterDuration: 200,
    exitDuration: 175,
    illustrateWith: "Прогнуться без боя или пробиваться смуте на зло?",
  },
  {
    sectionId: 41,
    timestamp: "00:58.75",
    line: "Эй, кто тебя поддержит, если ты в соло?",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Эй, кто тебя поддержит, если ты в соло?",
  },
  {
    sectionId: 42,
    timestamp: "01:00.75",
    line: "Как не забрать своё, когда при переменах",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Как не забрать своё, когда при переменах",
  },
  {
    sectionId: 43,
    timestamp: "01:02.45",
    line: "Твой незаменимый друг — это голод — он настроит",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Твой незаменимый друг — это голод — он настроит",
  },
  {
    sectionId: 44,
    timestamp: "01:04.45",
    line: "Лица в перекосы и путь тупиковый",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Лица в перекосы и путь тупиковый",
  },
  {
    sectionId: 45,
    timestamp: "01:06.15",
    line: "Биться нелегко, но в этом есть повод",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Биться нелегко, но в этом есть повод",
  },
  {
    sectionId: 46,
    timestamp: "01:07.95",
    line: "Выходить из грогги гордо",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Выходить из грогги гордо",
  },
  {
    sectionId: 47,
    timestamp: "01:09.00",
    line: "Бодряком на комбо побед",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Бодряком на комбо побед",
  },
  {
    sectionId: 48,
    timestamp: "01:10.45",
    line: "Резонные муки",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Резонные муки",
    isOverlay: true,
  },
  {
    sectionId: 49,
    timestamp: "01:11.45",
    line: "Правда в ногах, возьми себя в руки",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Правда в ногах, возьми себя в руки",
  },
  {
    sectionId: 50,
    timestamp: "01:13.25",
    line: "Стерпишь нокдаун — убьешь в себе rookie",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Стерпишь нокдаун — убьешь в себе rookie",
  },
  {
    sectionId: 51,
    timestamp: "01:15.10",
    line: "Держишь каркас, чердак на месте",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Держишь каркас, чердак на месте",
  },
  {
    sectionId: 52,
    timestamp: "01:16.50",
    line: "Значит ты готов к мести лучше чем Рокки",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Значит ты готов к мести лучше чем Рокки",
  },
  {
    sectionId: 53,
    timestamp: "01:18.70",
    line: "Дорогие суки, авто, дом, луки",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Дорогие суки, авто, дом, луки",
  },
  {
    sectionId: 54,
    timestamp: "01:20.45",
    line: "Думаешь об этом — делай потуги",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Думаешь об этом — делай потуги",
  },
  {
    sectionId: 55,
    timestamp: "01:22.20",
    line: "Жизнь — это бой за место под солнцем",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Жизнь — это бой за место под солнцем",
  },
  {
    sectionId: 56,
    timestamp: "01:23.80",
    line: "Даже в этом треке панчи и хуки",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Даже в этом треке панчи и хуки",
  },
  {
    sectionId: 57,
    timestamp: "01:25.70",
    line: "Подобно кабелю прятался в кавере, путался с мразями",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Подобно кабелю прятался в кавере, путался с мразями",
  },
  {
    sectionId: 58,
    timestamp: "01:28.45",
    line: "Воу-воу",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Воу-воу",
    isOverlay: true,
  },
  {
    sectionId: 59,
    timestamp: "01:29.25",
    line: "Казался каменным, делал все правильно, ведь падал по пути",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Казался каменным, делал все правильно, ведь падал по пути",
  },
  {
    sectionId: 60,
    timestamp: "01:31.95",
    line: "Воу-воу",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Воу-воу",
    isOverlay: true,
  },
  {
    sectionId: 61,
    timestamp: "01:32.85",
    line: "Страхи запрятаны, мечты загаданы, нервы закалены",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Страхи запрятаны, мечты загаданы, нервы закалены",
  },
  {
    sectionId: 62,
    timestamp: "01:35.40",
    line: "Как никогда мне перчатки затянуты",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Как никогда мне перчатки затянуты",
  },
  {
    sectionId: 63,
    timestamp: "01:37.25",
    line: "Левый и правый хук",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Левый и правый хук",
  },
  {
    sectionId: 64,
    timestamp: "01:38.20",
    line: "Воу-воу",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Воу-воу",
    isOverlay: true,
  },
  {
    sectionId: 65,
    timestamp: "01:38.85",
    line: "Вся жизнь — это",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Вся жизнь — это",
  },
  {
    sectionId: 66,
    timestamp: "01:39.55",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 67,
    timestamp: "01:40.15",
    line: "Затяжной, мучительный",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Затяжной, мучительный",
  },
  {
    sectionId: 68,
    timestamp: "01:41.35",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 69,
    timestamp: "01:42.00",
    line: "Агрессивный, жертвенный",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Агрессивный, жертвенный",
  },
  {
    sectionId: 70,
    timestamp: "01:43.10",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 71,
    timestamp: "01:43.80",
    line: "И не раз переломанный нос,",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "И не раз переломанный нос,",
  },
  {
    sectionId: 72,
    timestamp: "01:44.95",
    line: "Это лишь минимум, что может дать тебе",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Это лишь минимум, что может дать тебе",
  },
  {
    sectionId: 73,
    timestamp: "01:46.65",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "БОКС",
  },
  {
    sectionId: 74,
    timestamp: "01:47.25",
    line: "Каждый день как раунд в износ",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Каждый день как раунд в износ",
  },
  {
    sectionId: 75,
    timestamp: "01:48.60",
    line: "И не важно мне, B-Hope, Али, Тайсон, Рой Джонс",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "И не важно мне, B-Hope, Али, Тайсон, Рой Джонс",
  },
  {
    sectionId: 76,
    timestamp: "01:50.80",
    line: "Этот бой будет длиться пока не услышим последний гонг, — это",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "Этот бой будет длиться пока не услышим последний гонг, — это",
  },
  {
    sectionId: 77,
    timestamp: "01:53.80",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 78,
    timestamp: "01:54.20",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 79,
    timestamp: "01:54.65",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 80,
    timestamp: "01:55.10",
    line: "БОКС",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 81,
    timestamp: "01:55.60",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 82,
    timestamp: "01:55.90",
    line: "От этого нам некуда деться",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "От этого нам некуда деться",
  },
  {
    sectionId: 83,
    timestamp: "01:57.35",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 84,
    timestamp: "01:57.80",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 85,
    timestamp: "01:58.25",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 86,
    timestamp: "01:58.65",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 87,
    timestamp: "01:59.05",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 88,
    timestamp: "01:59.50",
    line: "Только не кидай полотенце",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Только не кидай полотенце",
  },
  {
    sectionId: 89,
    timestamp: "02:00.80",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 90,
    timestamp: "02:01.25",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 91,
    timestamp: "02:01.70",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 92,
    timestamp: "02:02.15",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 93,
    timestamp: "02:02.60",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 94,
    timestamp: "02:02.85",
    line: "Я готов оказаться в замесе",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Я готов оказаться в замесе",
  },
  {
    sectionId: 95,
    timestamp: "02:04.50",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 1,
  },
  {
    sectionId: 96,
    timestamp: "02:04.95",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 2,
  },
  {
    sectionId: 97,
    timestamp: "02:05.40",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 3,
  },
  {
    sectionId: 98,
    timestamp: "02:05.85",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 4,
  },
  {
    sectionId: 99,
    timestamp: "02:06.25",
    line: "БОКС",
    offsetEnter: -50,
    enterDuration: 50,
    exitDuration: 25,
    illustrateWith: "БОКС",
    sizeLevel: 5,
  },
  {
    sectionId: 100,
    timestamp: "02:06.65",
    line: "Только не кидай полотенце",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Только не кидай полотенце",
  },
  {
    sectionId: 101,
    timestamp: "02:08.05",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 102,
    timestamp: "02:10.10",
    line: "От этого нам некуда деться",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "От этого нам некуда деться",
  },
  {
    sectionId: 103,
    timestamp: "02:11.60",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 104,
    timestamp: "02:13.75",
    line: "Только не кидай полотенце",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Только не кидай полотенце",
  },
  {
    sectionId: 105,
    timestamp: "02:15.30",
    line: "*instrumental*",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 106,
    timestamp: "02:17.05",
    line: "Я готов оказаться в замесе",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Я готов оказаться в замесе",
  },
  {
    sectionId: 107,
    timestamp: "02:18.70",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 108,
    timestamp: "02:20.80",
    line: "Только не кидай полотенце",
    offsetEnter: -300,
    enterDuration: 300,
    exitDuration: 175,
    illustrateWith: "Только не кидай полотенце",
  },
  {
    sectionId: 109,
    timestamp: "02:22.30",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 110,
    timestamp: "02:35.70",
    line: "Вся жизнь — это",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "Вся жизнь — это",
  },
  {
    sectionId: 111,
    timestamp: "02:36.60",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 112,
    timestamp: "02:39.95",
    line: "[Voice] Come on!",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "[Voice] Come on!",
  },
  {
    sectionId: 113,
    timestamp: "02:40.70",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 114,
    timestamp: "02:43.50",
    line: "[Voice] Come on!",
    offsetEnter: -100,
    enterDuration: 100,
    exitDuration: 175,
    illustrateWith: "[Voice] Come on!",
  },
  {
    sectionId: 115,
    timestamp: "02:44.20",
    line: "*instrumental*",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "*instrumental*",
  },
  {
    sectionId: 116,
    timestamp: "02:50.65",
    line: "[Voice] Come on!",
    offsetEnter: -500,
    enterDuration: 500,
    exitDuration: 175,
    illustrateWith: "[Voice] Come on!",
  },
];
