import type { LyricsSection } from '@entities/track/model/types';
import type { RamBoxIllustrationDescriptor } from './types';

export const RAM_BOX_LYRICS: readonly LyricsSection<RamBoxIllustrationDescriptor>[] = [
  {
    sectionId: 1,
    sectionWidthPercent: 100,
    isOverlay: true,
    fullBleedIllustration: true,
    illustrationAnimation: { variant: 'instant' },
    timestamp: '00:00.000',
    line: '*instrumental*',
    illustrateWith: {
      descriptor: { kind: 'synced-video', src: '/animations/001-intro.mp4' },
      mediaType: 'custom',
    },
  },
  {
    sectionId: 2,
    continuing: true,
    sectionWidthPercent: 100,
    fullBleedIllustration: true,
    illustrationVisibility: 'only-active',
    illustrationAnimation: { variant: 'range', startPercent: 0, endPercent: 100, animationLengthPercent: 5 },
    timestamp: '00:14.250',
    line: '[Voice] Are You Ready?',
    illustrateWith: {
      descriptor: { kind: 'synced-video', src: '/animations/002-003-are-you-ready-ready-to-rumble.mp4' },
      mediaType: 'custom',
    },
  },
  {
    sectionId: 3,
    illustrationVisibility: 'active-end',
    illustrationAnimation: { variant: 'range', startPercent: 0, endPercent: 100, animationLengthPercent: 60 },
    timestamp: '00:22.500',
    line: "[Voice] Let's get ready to rumble!",
    illustrateWith: "[Voice] Let's get ready to rumble!",
  },
  {
    sectionId: 4,
    illustrationKind: 'kinetic-warp',
    illustrationVisibility: 'active-end',
    timestamp: '00:27.650',
    line: 'Вся жизнь — это',
    illustrateWith: 'Вся жизнь — это',
  },
  {
    sectionId: 5,
    sectionWidthPercent: 100,
    fullBleedIllustration: true,
    illustrationVisibility: 'adjacent',
    timestamp: '00:28.450',
    line: 'БОКС',
    illustrateWith: {
      descriptor: { kind: 'synced-video', src: '/animations/000-box.mp4' },
      mediaType: 'custom',
    },
  },
  {
    sectionId: 6,
    illustrationKind: 'vertical-typewriter',
    sectionWidthPercent: 15,
    illustrationVisibility: 'active-end',
    illustrationAnimation: { variant: 'range', startPercent: 0, endPercent: 100, animationLengthPercent: 31 },
    timestamp: '00:29.000',
    line: 'Затяжной, мучительный',
    illustrateWith: 'Затяжной, мучительный',
  },
  {
    sectionId: 7,
    sectionWidthPercent: 80,
    illustrationVisibility: 'adjacent',
    timestamp: '00:30.150',
    line: 'БОКС',
    illustrateWith: 'БОКС',
  },
  {
    sectionId: 8,
    background: {
      mediaType: 'video',
      src: '/animations/backgrounds/000-shared-bg-bloody.mp4',
    },
    sectionWidthPercent: 100,
    illustrationKind: 'blinking-words',
    illustrationVisibility: 'active-end',
    illustrationAnimation: {
      variant: 'range',
      startPercent: 0,
      endPercent: 100,
      animationLengthPercent: 60,
      wordStartPercents: [0, 60],
    },
    timestamp: '00:30.600',
    line: 'Агрессивный, жертвенный',
    illustrateWith: 'Агрессивный, жертвенный',
  },
  {
    sectionId: 9,
    illustrationVisibility: 'adjacent',
    timestamp: '00:31.700',
    line: 'БОКС',
    illustrateWith: 'БОКС',
  },
  {
    sectionId: 10,
    textBackgroundColor: 'dark-gray',
    textColor: 'toxic-carrot',
    background: {
      mediaType: 'video',
      src: '/animations/backgrounds/000-shared-bg-naive-film.mp4',
    },
    illustrationVisibility: 'active-end',
    illustrationKind: 'blinking-words',
    illustrationAnimation: {
      variant: 'range',
      startPercent: 0,
      endPercent: 100,
      animationLengthPercent: 50,
      wordStartPercents: [0, 20, 40, 60, 95],
    },
    timestamp: '00:32.380',
    line: 'И не раз переломанный нос,',
    illustrateWith: 'И не раз переломанный нос,',
  },
  {
    sectionId: 11,
    sectionWidthPercent: 100,
    illustrationKind: 'word-train',
    illustrationVisibility: 'active-end',
    illustrationAnimation: { variant: 'range', startPercent: 0, endPercent: 100, animationLengthPercent: 100 },
    timestamp: '00:34.150',
    line: 'Это лишь минимум, что может дать тебе',
    illustrateWith: 'Это лишь минимум, что может дать тебе',
  },
  {
    sectionId: 12,
    illustrationVisibility: 'adjacent',
    timestamp: '00:35.600',
    line: 'БОКС',
    illustrateWith: 'БОКС',
  },
  {
    sectionId: 13,
    illustrationVisibility: 'active-end',
    timestamp: '00:36.20',
    line: 'Каждый день как раунд в износ',
    illustrateWith: 'Каждый день как раунд в износ',
  },
  {
    sectionId: 14,
    timestamp: '00:37.305',
    line: 'И не важно мне, B-Hope, Али, Тайсон, Рой Джонс',
    illustrateWith: 'И не важно мне, B-Hope, Али, Тайсон, Рой Джонс',
  },
  {
    sectionId: 15,
    illustrationVisibility: "only-active",
    timestamp: '00:39.750',
    line: 'Этот бой будет длиться пока не услышим последний гонг, — это',
    illustrateWith: 'Этот бой будет длиться пока не услышим последний гонг, — это',
  },
  {
    sectionId: 16,
    sectionWidthPercent: 40,
    fullBleedIllustration: true,
    illustrationVisibility: 'adjacent',
    timestamp: '00:42.480',
    line: 'БОКС',
    illustrateWith: {
      descriptor: {
        kind: 'looping-video',
        loopStartTimeSeconds: 42.48,
        src: '/animations/box-x5-01/000-box-x5-01-01.mp4',
      },
      mediaType: 'custom',
    },
    sizeLevel: 1,
  },
  {
    sectionId: 17,
    sectionWidthPercent: 40,
    fullBleedIllustration: true,
    illustrationVisibility: 'adjacent',
    timestamp: '00:42.880',
    line: 'БОКС',
    illustrateWith: {
      descriptor: {
        kind: 'looping-video',
        loopStartTimeSeconds: 42.48,
        src: '/animations/box-x5-01/000-box-x5-01-02.mp4',
      },
      mediaType: 'custom',
    },
    sizeLevel: 2,
  },
  {
    sectionId: 18,
    sectionWidthPercent: 40,
    fullBleedIllustration: true,
    illustrationVisibility: 'adjacent',
    timestamp: '00:43.280',
    line: 'БОКС',
    illustrateWith: {
      descriptor: {
        kind: 'looping-video',
        loopStartTimeSeconds: 42.48,
        src: '/animations/box-x5-01/000-box-x5-01-03.mp4',
      },
      mediaType: 'custom',
    },
    sizeLevel: 3,
  },
  {
    sectionId: 19,
    sectionWidthPercent: 40,
    fullBleedIllustration: true,
    illustrationVisibility: 'adjacent',
    timestamp: '00:43.680',
    line: 'БОКС',
    illustrateWith: {
      descriptor: {
        kind: 'looping-video',
        loopStartTimeSeconds: 42.48,
        src: '/animations/box-x5-01/000-box-x5-01-04.mp4',
      },
      mediaType: 'custom',
    },
    sizeLevel: 4,
  },
  {
    sectionId: 20,
    sectionWidthPercent: 40,
    fullBleedIllustration: true,
    illustrationVisibility: 'adjacent',
    timestamp: '00:44.080',
    line: 'БОКС',
    illustrateWith: {
      descriptor: {
        kind: 'looping-video',
        loopStartTimeSeconds: 42.48,
        src: '/animations/box-x5-01/000-box-x5-01-05.mp4',
      },
      mediaType: 'custom',
    },
    sizeLevel: 5,
  },
  {
    sectionId: 21,
    illustrationAnimation: { variant: 'range', startPercent: 0, endPercent: 100, animationLengthPercent: 50 },
    illustrationVisibility: 'active-end',
    timestamp: '00:44.480',
    line: 'От этого нам некуда деться',
    illustrateWith: 'От этого нам некуда деться',
  },
  {
    sectionId: 22,
    background: { mediaType: 'solid', preset: 'cream-white' },
    textColor: 'dark-gray',
    illustrationVisibility: 'adjacent',
    timestamp: '00:46.200',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 1,
  },
  {
    sectionId: 23,
    background: { mediaType: 'solid', preset: 'arterial-red' },
    illustrationVisibility: 'adjacent',
    timestamp: '00:46.70',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 2,
  },
  {
    sectionId: 24,
    background: { mediaType: 'solid', preset: 'cream-white' },
    textColor: 'arterial-red',
    illustrationVisibility: 'adjacent',
    timestamp: '00:47.15',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 3,
  },
  {
    sectionId: 25,
    background: { mediaType: 'solid', preset: 'arterial-red' },
    textColor: 'toxic-carrot',
    illustrationVisibility: 'adjacent',
    timestamp: '00:47.60',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 4,
  },
  {
    sectionId: 26,
    illustrationVisibility: 'adjacent',
    timestamp: '00:48.05',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 5,
  },
  {
    sectionId: 27,
    illustrationVisibility: 'adjacent',
    illustrationKind: 'kinetic-warp',
    timestamp: '00:48.625',
    line: 'Только не кидай полотенце',
    illustrateWith: 'Только не кидай полотенце',
  },
  {
    sectionId: 28,
    background: { mediaType: 'solid', preset: 'arterial-red' },
    textColor: 'cream-white',
    illustrationVisibility: 'adjacent',
    timestamp: '00:49.850',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 1,
  },
  {
    sectionId: 29,
    textBackgroundColor: 'arterial-red',
    textColor: 'toxic-carrot',
    illustrationVisibility: 'adjacent',
    timestamp: '00:50.250',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 2,
  },
  {
    sectionId: 30,
    illustrationVisibility: 'adjacent',
    timestamp: '00:50.700',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 3,
  },
  {
    sectionId: 31,
    background: { mediaType: 'solid', preset: 'cream-white' },
    textColor: 'dark-gray',
    illustrationVisibility: 'adjacent',
    timestamp: '00:51.200',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 4,
  },
  {
    sectionId: 32,
    background: { mediaType: 'solid', preset: 'cream-white' },
    textColor: 'toxic-carrot',
    illustrationVisibility: 'active-end',
    timestamp: '00:51.600',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 5,
  },
  {
    sectionId: 33,
    illustrationAnimation: { variant: 'range', startPercent: 0, endPercent: 100, animationLengthPercent: 60 },
    illustrationVisibility: 'active-end',
    timestamp: '00:52.045',
    line: 'Я готов оказаться в замесе',
    illustrateWith: 'Я готов оказаться в замесе',
  },
  {
    sectionId: 34,
    illustrationVisibility: 'adjacent',
    timestamp: '00:53.35',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 1,
  },
  {
    sectionId: 35,
    illustrationVisibility: 'adjacent',
    timestamp: '00:53.78',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 2,
  },
  {
    sectionId: 36,
    illustrationVisibility: 'adjacent',
    timestamp: '00:54.21',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 3,
  },
  {
    sectionId: 37,
    illustrationVisibility: 'adjacent',
    timestamp: '00:54.64',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 4,
  },
  {
    sectionId: 38,
    illustrationVisibility: 'adjacent',
    timestamp: '00:55.07',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 5,
  },
  {
    sectionId: 39,
    illustrationVisibility: 'active-end',
    timestamp: '00:55.600',
    line: 'Только не кидай…',
    illustrateWith: 'Только не кидай…',
  },
  {
    sectionId: 40,
    timestamp: '00:56.400',
    line: 'Прогнуться без боя или пробиваться смуте на зло?',
    illustrateWith: 'Прогнуться без боя или пробиваться смуте на зло?',
  },
  {
    sectionId: 41,
    illustrationVisibility: 'active-end',
    timestamp: '00:58.75',
    line: 'Эй, кто тебя поддержит, если ты в соло?',
    illustrateWith: 'Эй, кто тебя поддержит, если ты в соло?',
  },
  {
    sectionId: 42,
    illustrationVisibility: 'active-end',
    timestamp: '01:00.75',
    line: 'Как не забрать своё, когда при переменах',
    illustrateWith: 'Как не забрать своё, когда при переменах',
  },
  {
    sectionId: 43,
    timestamp: '01:02.45',
    line: 'Твой незаменимый друг — это голод — он настроит',
    illustrateWith: 'Твой незаменимый друг — это голод — он настроит',
  },
  {
    sectionId: 44,
    illustrationVisibility: 'active-end',
    illustrationAnimation: { variant: 'range', startPercent: 0, endPercent: 100, animationLengthPercent: 70 },
    timestamp: '01:04.45',
    line: 'Лица в перекосы и путь тупиковый',
    illustrateWith: 'Лица в перекосы и путь тупиковый',
  },
  {
    sectionId: 45,
    illustrationVisibility: 'active-end',
    timestamp: '01:06.460',
    line: 'Биться нелегко, но в этом есть повод',
    illustrateWith: 'Биться нелегко, но в этом есть повод',
  },
  {
    sectionId: 46,
    timestamp: '01:07.95',
    line: 'Выходить из грогги гордо',
    illustrateWith: 'Выходить из грогги гордо',
  },
  {
    sectionId: 47,
    illustrationVisibility: 'only-active',
    timestamp: '01:09.00',
    line: 'Бодряком на комбо побед',
    illustrateWith: 'Бодряком на комбо побед',
  },
  {
    sectionId: 48,
    timestamp: '01:10.45',
    line: 'Резонные муки',
    illustrateWith: 'Резонные муки',
    isOverlay: true,
  },
  {
    sectionId: 49,
    illustrationVisibility: 'active-end',
    timestamp: '01:11.45',
    line: 'Правда в ногах, возьми себя в руки',
    illustrateWith: 'Правда в ногах, возьми себя в руки',
  },
  {
    sectionId: 50,
    illustrationKind: 'vertical-typewriter',
    illustrationVisibility: 'active-end',
    timestamp: '01:13.25',
    line: 'Стерпишь нокдаун — убьешь в себе rookie',
    illustrateWith: 'Стерпишь нокдаун — убьешь в себе rookie',
  },
  {
    sectionId: 51,
    illustrationVisibility: 'active-end',
    timestamp: '01:15.10',
    line: 'Держишь каркас, чердак на месте',
    illustrateWith: 'Держишь каркас, чердак на месте',
  },
  {
    sectionId: 52,
    timestamp: '01:16.50',
    line: 'Значит ты готов к мести лучше чем Рокки',
    illustrateWith: 'Значит ты готов к мести лучше чем Рокки',
  },
  {
    sectionId: 53,
    illustrationVisibility: 'active-end',
    timestamp: '01:18.70',
    line: 'Дорогие суки, авто, дом, луки',
    illustrateWith: 'Дорогие суки, авто, дом, луки',
  },
  {
    sectionId: 54,
    illustrationVisibility: 'active-end',
    timestamp: '01:20.45',
    line: 'Думаешь об этом — делай потуги',
    illustrateWith: 'Думаешь об этом — делай потуги',
  },
  {
    sectionId: 55,
    timestamp: '01:22.20',
    line: 'Жизнь — это бой за место под солнцем',
    illustrateWith: 'Жизнь — это бой за место под солнцем',
  },
  {
    sectionId: 56,
    illustrationVisibility: 'active-end',
    timestamp: '01:23.80',
    line: 'Даже в этом треке панчи и хуки',
    illustrateWith: 'Даже в этом треке панчи и хуки',
  },
  {
    sectionId: 57,
    illustrationVisibility: 'active-end',
    timestamp: '01:25.70',
    line: 'Подобно кабелю прятался в кавере, путался с мразями',
    illustrateWith: 'Подобно кабелю прятался в кавере, путался с мразями',
  },
  {
    sectionId: 58,
    timestamp: '01:28.45',
    line: 'Воу-воу',
    illustrateWith: 'Воу-воу',
    isOverlay: true,
  },
  {
    sectionId: 59,
    illustrationVisibility: 'only-active',
    timestamp: '01:29.25',
    line: 'Казался каменным, делал все правильно, ведь падал по пути',
    illustrateWith: 'Казался каменным, делал все правильно, ведь падал по пути',
  },
  {
    sectionId: 60,
    timestamp: '01:31.95',
    line: 'Воу-воу',
    illustrateWith: 'Воу-воу',
    isOverlay: true,
  },
  {
    sectionId: 61,
    illustrationVisibility: 'active-end',
    timestamp: '01:32.835',
    line: 'Страхи запрятаны, мечты загаданы, нервы закалены',
    illustrateWith: 'Страхи запрятаны, мечты загаданы, нервы закалены',
  },
  {
    sectionId: 62,
    illustrationVisibility: 'active-end',
    timestamp: '01:35.40',
    line: 'Как никогда мне перчатки затянуты',
    illustrateWith: 'Как никогда мне перчатки затянуты',
  },
  {
    sectionId: 63,
    timestamp: '01:37.250',
    line: 'Левый и правый хук',
    illustrateWith: 'Левый и правый хук',
  },
  {
    sectionId: 64,
    timestamp: '01:38.20',
    line: 'Воу-воу',

    illustrateWith: 'Воу-воу',
    isOverlay: true,
  },
  {
    sectionId: 65,
    illustrationVisibility: 'active-end',
    timestamp: '01:38.85',
    line: 'Вся жизнь — это',
    illustrateWith: 'Вся жизнь — это',
  },
  {
    sectionId: 66,
    illustrationVisibility: 'active-end',
    timestamp: '01:39.55',
    line: 'БОКС',
    illustrateWith: 'БОКС',
  },
  {
    sectionId: 67,
    background: {
      mediaType: 'video',
      src: '/animations/backgrounds/000-shared-bg-bloody.mp4',
    },
    illustrationVisibility: 'active-end',
    timestamp: '01:40.15',
    line: 'Затяжной, мучительный',
    illustrateWith: 'Затяжной, мучительный',
  },
  {
    sectionId: 68,
    illustrationVisibility: 'active-end',
    timestamp: '01:41.35',
    line: 'БОКС',
    illustrateWith: 'БОКС',
  },
  {
    sectionId: 69,
    background: {
      mediaType: 'video',
      src: '/animations/backgrounds/000-shared-bg-bloody.mp4',
    },
    timestamp: '01:42.00',
    line: 'Агрессивный, жертвенный',
    illustrateWith: 'Агрессивный, жертвенный',
  },
  {
    sectionId: 70,
    illustrationVisibility: 'active-end',
    timestamp: '01:43.10',
    line: 'БОКС',
    illustrateWith: 'БОКС',
  },
  {
    sectionId: 71,
    illustrationVisibility: 'active-end',
    timestamp: '01:43.80',
    line: 'И не раз переломанный нос,',
    illustrateWith: 'И не раз переломанный нос,',
  },
  {
    sectionId: 72,
    illustrationVisibility: 'active-end',
    timestamp: '01:44.95',
    line: 'Это лишь минимум, что может дать тебе',
    illustrateWith: 'Это лишь минимум, что может дать тебе',
  },
  {
    sectionId: 73,
    illustrationVisibility: 'active-end',
    timestamp: '01:46.65',
    line: 'БОКС',
    illustrateWith: 'БОКС',
  },
  {
    sectionId: 74,
    timestamp: '01:47.25',
    line: 'Каждый день как раунд в износ',
    illustrateWith: 'Каждый день как раунд в износ',
  },
  {
    sectionId: 75,
    illustrationVisibility: 'active-end',
    timestamp: '01:48.60',
    line: 'И не важно мне, B-Hope, Али, Тайсон, Рой Джонс',
    illustrateWith: 'И не важно мне, B-Hope, Али, Тайсон, Рой Джонс',
  },
  {
    sectionId: 76,
    illustrationVisibility: 'active-end',
    timestamp: '01:50.80',
    line: 'Этот бой будет длиться пока не услышим последний гонг, — это',
    illustrateWith: 'Этот бой будет длиться пока не услышим последний гонг, — это',
  },
  {
    sectionId: 77,
    illustrationVisibility: 'active-end',
    timestamp: '01:53.80',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 1,
  },
  {
    sectionId: 78,
    illustrationKind: 'kinetic-warp',
    timestamp: '01:54.20',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 2,
  },
  {
    sectionId: 79,
    illustrationVisibility: 'active-end',
    timestamp: '01:54.65',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 3,
  },
  {
    sectionId: 80,
    illustrationVisibility: 'active-end',
    timestamp: '01:55.10',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 4,
  },
  {
    sectionId: 81,
    illustrationVisibility: 'active-end',
    timestamp: '01:55.60',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 5,
  },
  {
    sectionId: 82,
    timestamp: '01:55.90',
    line: 'От этого нам некуда деться',
    illustrateWith: 'От этого нам некуда деться',
  },
  {
    sectionId: 83,
    illustrationVisibility: 'active-end',
    timestamp: '01:57.35',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 1,
  },
  {
    sectionId: 84,
    illustrationVisibility: 'active-end',
    timestamp: '01:57.80',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 2,
  },
  {
    sectionId: 85,
    illustrationVisibility: 'active-end',
    timestamp: '01:58.25',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 3,
  },
  {
    sectionId: 86,
    illustrationVisibility: 'active-end',
    timestamp: '01:58.65',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 4,
  },
  {
    sectionId: 87,
    illustrationVisibility: 'active-end',
    timestamp: '01:59.05',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 5,
  },
  {
    sectionId: 88,
    illustrationVisibility: 'active-end',
    timestamp: '01:59.50',
    line: 'Только не кидай полотенце',
    illustrateWith: 'Только не кидай полотенце',
  },
  {
    sectionId: 89,
    illustrationVisibility: 'active-end',
    timestamp: '02:00.80',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 1,
  },
  {
    sectionId: 90,
    illustrationVisibility: 'active-end',
    timestamp: '02:01.25',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 2,
  },
  {
    sectionId: 91,
    illustrationVisibility: 'active-end',
    timestamp: '02:01.70',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 3,
  },
  {
    sectionId: 92,
    illustrationVisibility: 'active-end',
    timestamp: '02:02.15',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 4,
  },
  {
    sectionId: 93,
    illustrationVisibility: 'active-end',
    timestamp: '02:02.60',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 5,
  },
  {
    sectionId: 94,
    illustrationVisibility: 'active-end',
    timestamp: '02:02.85',
    line: 'Я готов оказаться в замесе',
    illustrateWith: 'Я готов оказаться в замесе',
  },
  {
    sectionId: 95,
    illustrationVisibility: 'active-end',
    timestamp: '02:04.50',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 1,
  },
  {
    sectionId: 96,
    illustrationVisibility: 'active-end',
    timestamp: '02:04.95',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 2,
  },
  {
    sectionId: 97,
    illustrationVisibility: 'active-end',
    timestamp: '02:05.40',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 3,
  },
  {
    sectionId: 98,
    illustrationVisibility: 'active-end',
    timestamp: '02:05.85',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 4,
  },
  {
    sectionId: 99,
    illustrationVisibility: 'active-end',
    timestamp: '02:06.25',
    line: 'БОКС',
    illustrateWith: 'БОКС',
    sizeLevel: 5,
  },
  {
    sectionId: 100,
    timestamp: '02:06.65',
    line: 'Только не кидай полотенце',
    illustrateWith: 'Только не кидай полотенце',
  },
  {
    sectionId: 101,
    illustrationVisibility: 'active-end',
    timestamp: '02:08.05',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 102,
    illustrationVisibility: 'active-end',
    timestamp: '02:10.10',
    line: 'От этого нам некуда деться',
    illustrateWith: 'От этого нам некуда деться',
  },
  {
    sectionId: 103,
    illustrationVisibility: 'active-end',
    timestamp: '02:11.60',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 104,
    illustrationVisibility: 'active-end',
    timestamp: '02:13.75',
    line: 'Только не кидай полотенце',
    illustrateWith: 'Только не кидай полотенце',
  },
  {
    sectionId: 105,
    illustrationVisibility: 'active-end',
    timestamp: '02:15.30',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 106,
    timestamp: '02:17.05',
    line: 'Я готов оказаться в замесе',
    illustrateWith: 'Я готов оказаться в замесе',
  },
  {
    sectionId: 107,
    illustrationVisibility: 'active-end',
    timestamp: '02:18.70',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 108,
    illustrationVisibility: 'active-end',
    timestamp: '02:20.80',
    line: 'Только не кидай полотенце',
    illustrateWith: 'Только не кидай полотенце',
  },
  {
    sectionId: 109,
    illustrationVisibility: 'active-end',
    timestamp: '02:22.30',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 110,
    illustrationVisibility: 'active-end',
    timestamp: '02:35.70',
    line: 'Вся жизнь — это',
    illustrateWith: 'Вся жизнь — это',
  },
  {
    sectionId: 111,
    illustrationVisibility: 'active-end',
    timestamp: '02:36.60',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 112,
    timestamp: '02:39.95',
    line: '[Voice] Come on!',
    illustrateWith: '[Voice] Come on!',
  },
  {
    sectionId: 113,
    illustrationVisibility: 'active-end',
    timestamp: '02:40.70',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 114,
    illustrationVisibility: 'active-end',
    timestamp: '02:43.50',
    line: '[Voice] Come on!',
    illustrateWith: '[Voice] Come on!',
  },
  {
    sectionId: 115,
    illustrationVisibility: 'active-end',
    timestamp: '02:44.20',
    line: '*instrumental*',
    illustrateWith: '*instrumental*',
  },
  {
    sectionId: 116,
    illustrationVisibility: 'active-end',
    timestamp: '02:50.65',
    line: '[Voice] Come on!',
    illustrateWith: '[Voice] Come on!',
  },
];
